---

extends:
  - airbnb
  - "plugin:jest/recommended"
  - "plugin:react/recommended"
  - "plugin:flowtype/recommended"
  
plugins:
  - flowtype

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

rules:
  import/no-unresolved: [2, { ignore: ['^gon$'] }]
  import/extensions: [2, { ignore: ['^gon$'] }]
